POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Bob",
  "email": "bob@bob.com",
  "password": "password",
  "password_confirmation": "password"
}


###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bob@bob.com",
  "password": "password"
}